---
- name: Install openVPN
  become: true
  apt: 
    name: ['openvpn=2.3.10-1ubuntu2.1']
    install_recommends: yes
  register: apt_openvpnclientinstall

- name: Enable OpenVpnClient
  become: true
  systemd:
    name: openvpn
    enabled: true
  notify: openvpn_client_is_enabled
  when: apt_openvpnclientinstall.changed

