---
- name: Add openvpnclient config
  become: true
  template: src="{{ item }}.j2" dest="/{{ item }}"
  with_items:
    - "etc/openvpn/client.conf"
  notify: reload openvpnclient
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release  == 'xenial'

- name: collect facts about system services
  service_facts:
  register: services_state

- name: Debug
  debug:
    var: services_state[openvpn]
