---
- name: Add openvpnclient config
  become: true
  template: src="{{ item }}.j2" dest="/{{ item }}"
  with_items:
    - "etc/openvpn/client.conf"
  notify: reload openvpnclient
- name: Enable openvpn client
  become: true
  systemd:
    name: openvpn
    enabled: true
