- name: Extract config and keys
  become: true
  unarchive: 
    src: "{{ inventory_hostname }}.tar.gz"
    dest: "{{ openvpn_client_etc_dir }}"
    owner: root
    group: root
    mode: 0600
  notify: reload openvpn
  #when: ansible_distribution == 'Ubuntu' and ansible_distribution_release  == 'xenial'

