---
- name: Add openvpnclient config
  become: true
  template: src="{{ item }}.j2" dest="/{{ item }}"
  with_items:
    - "etc/openvpn/client.conf"
  notify: reload openvpnclient
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version  == '16.04'
