---
- name: Add openvpnclient config
  become: true
  template: src="{{ item }}.j2" dest="/{{ item }}"
  with_items:
    - "etc/openvpn/client.conf"
  notify: 
  - reload openvpn
  - collect facts about system services
  - Debug
    
