---
- name: enable openvpn service
  become: true
  systemd:
    name: openvpn
    enabled: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release  == 'xenial'
  debug: msg="openvpn added to autostart"