---
- name: enable_openvpn_service
  become: true
  systemd:
    name: openvpn
    enabled: true

- name: Show startup status openvpn clien
  debug: "msg='OpenVPN Clien is enabled for startup on boot'"
  listen: enable_openvpn_service