---
- name: reload openvpnclient
  systemd: 
   state: restarted
   name: openvpn
  
- name: enable openvpn service
  become: true
  systemd:
    name: openvpn
    enabled: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release  == 'xenial'
