---
- name: OpenVPNClien_Status
  service_facts:
  register: services_state

- name: Debug
  debug:
    var: ansible_facts.services['openvpn']

- name: openvpn_client_is_enabled
  debug: "msg='OpenVPN Client added to autostart'"

