---
- name: reload openvpn
  become: yes
#  systemd: name=openvpn state=restarted
  service: name=openvpn state=started enabled=yes

- name: collect facts about system services
  service_facts:
  register: services_state
  listen: reload_openvpn 

- name: Debug
  debug:
    var: ansible_facts.services['openvpn']
  listen: reload_openvpn
