---
- name: reload_openvpn
  become: yes
  service: 
    name: openvpn.service
    state: restarted
  
- name: collect facts about system services
  service_facts:
  register: services_state
  listen: reload_openvpn 

- name: Debug
  debug:
    var: ansible_facts.services['openvpn.service']
  listen: reload_openvpn
